# Generated by Django 3.0.8 on 2022-10-14 08:57

import divine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_name', models.CharField(max_length=30, unique=True)),
                ('customer', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('composition_exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_name', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=30)),
                ('supplier', models.CharField(max_length=30)),
                ('compliance', models.CharField(max_length=30)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('issued_to', models.CharField(max_length=30)),
                ('machine_no', models.CharField(max_length=10)),
                ('total_weight', models.FloatField()),
                ('no_of_batches', models.IntegerField()),
                ('fg', models.ForeignKey(db_column='fg', on_delete=django.db.models.deletion.CASCADE, to='divine.FinishedGoods')),
            ],
        ),
        migrations.CreateModel(
            name='Compositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('KG', 'Kg'), ('GM', 'Gm'), ('MG', 'Mg')], default='KG', max_length=2)),
                ('fg', models.ForeignKey(db_column='fg', on_delete=django.db.models.deletion.CASCADE, to='divine.FinishedGoods')),
                ('rm', models.ForeignKey(db_column='rm', on_delete=django.db.models.deletion.CASCADE, to='divine.RawMaterials')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('mfa_hash', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', divine.models.UserManager()),
            ],
        ),
    ]
