name: CICD Talk Project

on: [push]
    # paths:
    #   - docker/**
    #   - app/**

jobs:

  build_deploy_docker_image:
    name: Build and Deploy Docker Image
    runs-on:  ubuntu-latest

    steps:
      - name:  Checkout the Repo
        uses:  actions/checkout@v4

      - name: Build Image
        run:  |
          docker build -f ./docker/Dockerfile -t admin-app:test.0.1 .
      
      # - name: Trivy Check on Docker
      #   uses: aquasecurity/trivy-action@0.33.1
      #   with:
      #     image-ref:  'admin-app:test.0.1'
      #     format: 'table'
      #     exit-code:  '1'
      #     ignore-unfixed: true
      #     vuln-type:  'os,library'
      #     severity: 'CRITICAL,HIGH'

      - name: Push Image to Docker Hub
        env:
          docker_pat: ${{ secrets.DOCKER_PAT}}
        run:  |
          docker tag admin-app:test.0.1 dhiverse/admin-app:test.0.1
          echo $docker_pat | docker login --username dhiverse --password-stdin
          push dhiverse/admin-app:test.0.1 

